### ISSUE TITLE
python train/train_full.py ValueError: cannot reshape array of size 230400 into shape (64,64,newaxis)

### ISSUE THREAD

**Issue by zhang123-sys** [luwanglin/GaitSet_learning#4]
![image](https://user-images.githubusercontent.com/63956071/188188209-02cd2a01-094f-4769-a5eb-af84381c7ed3.png)

**Comment by zhang123-sys** [comment]
![image](https://user-images.githubusercontent.com/63956071/188195396-6ba8ab56-3c8b-4dfd-80b2-c483df7dd762.png)
Traceback (most recent call last):
  File "C:\Users\hp\Miniconda3\envs\torch1.10\lib\site-packages\visdom\__init__.py", line 708, in _send
    return self._handle_post(
  File "C:\Users\hp\Miniconda3\envs\torch1.10\lib\site-packages\visdom\__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "C:\Users\hp\Miniconda3\envs\torch1.10\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\hp\Miniconda3\envs\torch1.10\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\hp\Miniconda3\envs\torch1.10\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\hp\Miniconda3\envs\torch1.10\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/full (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002887D4EA310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[WinError 10061] 由于目标计算机积极拒绝，无法连接。
